config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Публичные страницы
  get "pages/home"
  get "pages/about"
  resources :subscriptions, only: :create

  # Страницы просмотра
  get "timeline", to: "memories#timeline"
  get "family_web", to: "memories#family_web"
  get "family_tree", to: "family_tree#index"
  get "family_tree/:id", to: "family_tree#show", as: :family_tree_member

  get "profile", to: "profile#my", as: "my_profile"
  get "profile/edit", to: "profile#edit", as: "edit_profile"
  patch "profile/update", to: "profile#update", as: "update_profile"

  resources :profile, only: [ :show ]

  # CRUD для родственников
  resources :family_members

  # CRUD для воспоминаний
  resources :memories do
    collection do
      get "my"
      get "by_tag/:tag", to: "by_tag", as: "by_tag"
    end
  end

  # Комментарии
  resources :comments, only: [ :show, :create, :edit, :update, :destroy ]

  # Админская часть
  namespace :admin do
    # Страницы просмотра
    get "timeline", to: "memories#timeline"
    get "family_web", to: "memories#family_web"
    get "family_tree", to: "family_tree#index"
    get "family_tree/:id", to: "family_tree#show", as: :admin_family_tree_member

    # CRUD для родственников
    resources :family_members

    # CRUD для воспоминаний
    resources :memories do
      resources :comments
    end

    # Подписки
    resources :subscriptions
  end

  # API
  namespace :api, format: "json" do
    namespace :v1 do
      resources :subscriptions
      get "welcome/index"
      get "welcome/preview"

      devise_scope :user do
        post "sign_up",          to: "registrations#create"
        post "sign_in",          to: "sessions#create"
        get  "authorize_by_jwt", to: "sessions#authorize_by_jwt"
        get  "sign_out",         to: "sessions#destroy"
      end
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Главная
  # Defines the root path route ("/")
  root "pages#home"
end

app/controllers/admin/family_tree_controller.rb
class Admin::FamilyTreeController < ApplicationController
  load_and_authorize_resource :family_member, only: [ :index, :show ]
  def index
    @members = FamilyMember.all
  end

  def show
    @member = FamilyMember.find(params[:id])
  end
end

app/controllers/family_tree_controller.rb
class FamilyTreeController < ApplicationController
  load_and_authorize_resource :family_member, only: [ :index, :show ]

  def index
    @members = current_user.family.family_members

    set_meta_tags(
      title: "Семейное древо",
      description: "Полная история вашей семьи и родственные связи",
      keywords: "family, tree, genealogy, relatives",
      og: {
        title: "Семейное древо",
        type: "website",
        url: family_tree_url
      }
    )
  end

  def show
    @member = current_user.family.family_members.find(params[:id])
    @memories = @member.memories.order(date: :desc)

    set_meta_tags(
      title: @family_member.to_s,
      description: "Информация и воспоминания о #{@family_member}",
      keywords: "family, member",
      og: {
        title: @family_member.to_s,
        type: "website",
        url: family_tree_url(@family_member)
      }
    )
  end
end

app/helpers/family_tree_helper.rb
module FamilyTreeHelper
end

app/views/family_tree/index.html.erb
<section class="ShiftLeft">
  <h1>Семейное древо — список всех членов</h1>
  
  <%= link_to 'Создать новую связь', new_family_member_path %>
  
  <ul>
    <% @members.each do |member| %>
      <li>
        <%= link_to "#{member.relation} #{member.name}", family_tree_member_path(member) %>
      </li>
    <% end %>
  </ul>
</section>

app/views/family_tree/show.html.erb
<section class="ShiftLeft">
  <h1><%= @member.name %></h1>
  
  <h2>Родители:</h2>
  <ul>
    <li>Мама: <%= @member.mother&.name || "-" %></li>
    <li>Папа: <%= @member.father&.name || "-" %></li>
  </ul>
  
  <h2>Супруг/супруга:</h2>
  <p>
    <%= @member.spouse&.name || "-" %>
  </p>
  
  <h2>Дети:</h2>
  <ul>
    <% @member.children.each do |child| %>
      <li><%= child.name %></li>
    <% end %>
  </ul>
  
  <h2>Братья/сёстры:</h2>
  <ul>
    <% @member.siblings.each do |sibling| %>
      <li><%= sibling.name %></li>
    <% end %>
  </ul>
  
  <hr>

  <div>
    <%= link_to "Edit this family member", edit_family_member_path(@member) %> |
    <%= link_to "Back to family tree", timeline_path %>
    <%= link_to "Destroy this family member", @member, data: { turbo_stream: false, turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
  </div>

   <hr>

  <h2>Воспоминания:</h2>

  <% if @memories.any? %>
    <ul style="list-style: none; padding: 0;">
      <% @memories.each do |memory| %>
        <li style="margin-bottom: 25px;">

          <%= link_to memory_path(memory) do %>
            <%= image_tag memory.image.url, width: 200, style: "display: block; margin-bottom: 8px;" %>
          <% end %>

          <div style="font-weight: bold; font-size: 18px; margin-bottom: 4px;">
            <%= memory.title %>
          </div>

          <div style="margin-bottom: 6px;">
            <%= memory.body %>
          </div>

          <section>
            <%= memory.date.strftime("%d.%m.%Y") %>
          </div>

        </li>
      <% end %>
    </ul>
  <% else %>
    <p>Пока нет воспоминаний.</p>
  <% end %>

</section>