config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Публичные страницы
  get "pages/home"
  get "pages/about"
  resources :subscriptions, only: :create

  # Страницы просмотра
  get "timeline", to: "memories#timeline"
  get "family_web", to: "memories#family_web"
  get "family_tree", to: "family_tree#index"
  get "family_tree/:id", to: "family_tree#show", as: :family_tree_member

  get "profile", to: "profile#my", as: "my_profile"
  get "profile/edit", to: "profile#edit", as: "edit_profile"
  patch "profile/update", to: "profile#update", as: "update_profile"

  resources :profile, only: [ :show ]

  # CRUD для родственников
  resources :family_members

  # CRUD для воспоминаний
  resources :memories do
    collection do
      get "my"
      get "by_tag/:tag", to: "by_tag", as: "by_tag"
    end
  end

  # Комментарии
  resources :comments, only: [ :show, :create, :edit, :update, :destroy ]

  # Админская часть
  namespace :admin do
    # Страницы просмотра
    get "timeline", to: "memories#timeline"
    get "family_web", to: "memories#family_web"
    get "family_tree", to: "family_tree#index"
    get "family_tree/:id", to: "family_tree#show", as: :admin_family_tree_member

    # CRUD для родственников
    resources :family_members

    # CRUD для воспоминаний
    resources :memories do
      resources :comments
    end

    # Подписки
    resources :subscriptions
  end

  # API
  namespace :api, format: "json" do
    namespace :v1 do
      resources :subscriptions
      get "welcome/index"
      get "welcome/preview"

      devise_scope :user do
        post "sign_up",          to: "registrations#create"
        post "sign_in",          to: "sessions#create"
        get  "authorize_by_jwt", to: "sessions#authorize_by_jwt"
        get  "sign_out",         to: "sessions#destroy"
      end
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Главная
  # Defines the root path route ("/")
  root "pages#home"
end

app/models/memory.rb
class Memory < ApplicationRecord
  belongs_to :family
  belongs_to :family_member

  has_many :comments, as: :commentable, dependent: :destroy

  mount_uploader :image, MemoryImageUploader
  acts_as_taggable_on :tags
  acts_as_taggable_on :categories

  validates :title, :image, :date, presence: true

  def as_json
    {
      id: id,
      body: body,
      date: date,
      family_member: family_member.to_s,
      image_url: image.url
    }
  end
end

app/controllers/admin/memories_controller.rb
class Admin::MemoriesController < ApplicationController
  load_and_authorize_resource
  before_action :set_memory, only: %i[ show edit update destroy ]

  def timeline
    @memories_by_year = if current_user.admin?
      Memory.all.order(:date).group_by { |m| m.date.year }
    end
  end
  def family_web
    @memories =  Memory.all
  end

  def family_tree
  end

  # GET /memories or /memories.json
  def index
    @memories = Memory.all
  end

  # GET /memories/1 or /memories/1.json
  def show
  end

  # GET /memories/new
  def new
    @memory = Memory.new
  end

  # GET /memories/1/edit
  def edit
  end

  # POST /memories or /memories.json
  def create
    @memory = Memory.new(memory_params)
    @memory.family = current_user.family

    respond_to do |format|
      if @memory.save
        format.html { redirect_to [ :admin, @memory ], notice: "Memory was successfully created." }
        format.json { render :show, status: :created, location: @memory }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @memory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /memories/1 or /memories/1.json
  def update
    respond_to do |format|
      if @memory.update(memory_params)
        format.html { redirect_to [ :admin, @memory ], notice: "Memory was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @memory }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @memory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memories/1 or /memories/1.json
  def destroy
    @memory.destroy!

    respond_to do |format|
      format.html { redirect_to admin_timeline_path, notice: "Memory was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_memory
      @memory = Memory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def memory_params
        params.require(:memory).permit(:title, :family_member_id, :body, :date, :image)
    end
end

app/controllers/memories_controller.rb
class MemoriesController < ApplicationController
  load_and_authorize_resource
  before_action :set_memory, only: %i[ show edit update destroy ]

  def timeline
    if current_user.family
      @memories_by_year = current_user.family.memories
        .order(:date)
        .group_by { |m| m.date.year }
    else
      @memories_by_year = {}
    end

    # Мета-теги для страницы «Лента времени»
    set_meta_tags(
      title: "Лента времени",
      description: "Просмотр всех воспоминаний вашей семьи в хронологическом порядке",
      keywords: "family, memories, timeline",
      og: {
        title: "Лента времени",
        type: "website",
        url: timeline_url
      }
    )
  end

  def family_web
    if current_user.family
      @memories = current_user.family.memories.order(:date)
    else
      @memories = Memory.none
    end

    set_meta_tags(
      title: "Сеть семейных воспоминаний",
      description: "Просмотр всех воспомианий вашей семьи",
      keywords: "family, web, relatives, memories",
      og: {
        title: "Сеть семейных воспоминаний",
        type: "website",
        url: family_web_url
      }
  )
  end

  def my
    @memories = current_user.memories.order(created_at: :desc)
    render :index

    set_meta_tags(
      title: "Мои воспоминания",
      description: "Просмотр всех воспоминаний, созданных вами",
      keywords: "family, memories",
      og: {
        title: "Мои воспоминания",
        type: "website",
        url: my_memories_url
      }
  )
  end

  def by_tag
    @memories = Memory.tagged_with(params[:tag])
    render :index
  end

  def new
    @memory = Memory.new
  end

  def create
    @memory = Memory.new(memory_params)
    @memory.family = current_user.family

    respond_to do |format|
      if @memory.save
        format.html { redirect_to @memory, notice: "Memory was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    if @memory.update(memory_params)
      redirect_to @memory, notice: "Memory was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @memory.destroy
    redirect_to timeline_path, notice: "Memory was successfully destroyed."
  end

  private

  def set_memory
    @memory = Memory.find(params[:id])
  end

  def memory_params
    params.require(:memory).permit(:title, :family_member_id, :body, :date, :image, :tag_list, :category_list)
  end
end

app/helpers/admin/memories_helper.rb
module Admin::MemoriesHelper
end

app/helpers/memories_helper.rb
module MemoriesHelper
end

app/views/memories/_form.html.erb
<%= form_with(model: memory) do |form| %>
  <% if memory.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(memory.errors.count, "error") %> prohibited this memory from being saved:</h2>

      <ul>
        <% memory.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :family_member_id, "Family member" %>
    <%= form.collection_select :family_member_id, current_user.family.family_members.order(:name), :id, :to_s %>
  </div>

  <div>
    <%= form.label :category_list, style: "display: block" %>
    <%= form.select :category_list, [["Summer", "Summer"], ["Childhood", "Childhood"], ["Pets", "Pets"], ["Holidays", "Holidays"]] %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.textarea :body %>
  </div>

  <div>
    <%= form.label :tag_list, style: "display: block" %>
    <%= form.text_field :tag_list %>
  </div>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.file_field :image %>
  </div>

  <div>
    <%= form.label :date, style: "display: block" %>
    <%= form.date_field :date, required: true %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/memories/_memory.html.erb
<div id="<%= dom_id memory %>">

  <h2><%= memory.title %></h2>
  <p><%= memory.body %></p>
  <p>
  <% if memory.family_member.user&.profile %>
    <%= link_to \
      "#{memory.family_member.to_s}",
      profile_path(memory.family_member.user.profile)
    %>
  <% else %>
    <%= memory.family_member.name %>
  <% end %>
</p>
<p><%= memory.date %></p>

  <p>
    <% memory.tag_list.each do |tag| %>
      <%= link_to tag, by_tag_memories_path(tag) %>
    <% end %>
  </p>

<%= image_tag memory.image.q70.url, width: 300 %>

</div>

app/views/memories/edit.html.erb
<section class="ShiftLeft">
  <% content_for :title, "Editing memory" %>
  
  <h1>Editing memory</h1>
  
  <%= render "form", memory: @memory %>
  
  <br>
  
  <div>
    <%= link_to "Show this memory", @memory%> |
    <%= link_to "Back to memories", timeline_path %>
  </div>
</section>

app/views/memories/family_web.html.erb
<section class="ShiftLeft">
  <h1>Сеть воспоминаний</h1>
  
  <%= link_to 'Создать воспоминание', new_memory_path %>
  
  <div class="family_tree">
    <% @memories.each do |memory| %>
      <div class="family_tree-item">
  
        <% if memory.body.present? %>
          <p class="memory-text"><%= memory.body %></p>
            <b>
              <% if memory.family_member.user&.profile %>
                <%= link_to \
                  "#{memory.family_member.to_s}",
                  profile_path(memory.family_member.user.profile)
                %>
              <% else %>
                <%= memory.family_member.name %>
              <% end %>
            </b>
        <% end %>
  
        <div class="memory-image">
          <%= link_to memory do %>
              <%= image_tag memory.image.q70.url, width: 300 %>
          <% end %>
          </div>
  
      </div>
    <% end %>
  </div>
</section>

app/views/memories/index.html.erb
<section class="ShiftLeft">
  <p style="color: green"><%= notice %></p>
  
  <% content_for :title, "Memories" %>
  
  <h1>Memories</h1>

  <div>
    <%= link_to "All memories", memories_path %>
    
    <% Memory.tag_counts_on(:categories).each do |tag| %>
      <%= link_to tag.name, by_tag_memories_path(tag.name) %>
    <% end %>
  </div>

  <hr>
  
  <%= link_to 'Создать воспоминание', new_memory_path %>
  
  <div id="memories">
    <% @memories.each do |memory| %>
      <%= render memory %>
      <p>
        <%= link_to "Show this memory", memory %>
      </p>
    <% end %>
  </div>
  
  <%= link_to "New memory", new_memory_path %>
</section>

app/views/memories/new.html.erb
<section class="ShiftLeft">
  <% content_for :title, "New memory" %>
  
  <h1>New memory</h1>
  
  <%= render "form", memory: @memory %>
  
  <br>
  
  <div>
    <%= link_to "Back to memories", timeline_path %>
  </div>
</section>

app/views/memories/show.html.erb
<%
  set_meta_tags(
    title: @memory_name,
    description: "Воспоминание твоей семьи",
    keywords: "family, memory",
    og: {
      title: @memory_name,
      type: "website",
      url: memory_url(@memory)
    }
  )
%>

<section class="ShiftLeft">
  <p style="color: green"><%= notice %></p>
  
  <%= render @memory %>
  
  <div>
    <%= link_to "Edit this memory", edit_memory_path(@memory) %> |
    <%= link_to "Back to memories", timeline_path %>
  
    <%= link_to "Destroy this memory", @memory, data: { turbo_stream: false, turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
  </div>
  
  <%= render "comments/comments", commentable: @memory %> 
</section>

app/views/memories/timeline.html.erb
<section class="ShiftLeft">
  <h1>Лента времени</h1>

  <div>
    <%= link_to "All memories", memories_path %>
    
    <% Memory.tag_counts_on(:categories).each do |tag| %>
      <%= link_to tag.name, by_tag_memories_path(tag.name) %>
    <% end %>
  </div>

  <hr>
  
  <%= link_to 'Создать воспоминание', new_memory_path %>
  
  <div class="timeline">
    <% @memories_by_year.each do |year, memories| %>
      <div class="timeline-year">
        <h2><%= year %></h2>
  
        <% memories.each do |memory| %>
          <div class="timeline-item">
            <h3>
              <% if memory.family_member.user&.profile %>
                <%= link_to \
                  "#{memory.family_member.to_s}",
                  profile_path(memory.family_member.user.profile)
                %>
              <% else %>
                <%= memory.family_member.name %>
              <% end %>
            </h3>
  
            <div class="memory-image">
              <%= link_to memory do %>
                <%= image_tag memory.image.q70.url, width: 300 %>
              <% end %>
            </div>
  
            <p><%= l(memory.date, format: :long) %></p>
            <p><%= memory.body %></p>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</section>