config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Публичные страницы
  get "pages/home"
  get "pages/about"
  resources :subscriptions, only: :create

  # Страницы просмотра
  get "timeline", to: "memories#timeline"
  get "family_web", to: "memories#family_web"
  get "family_tree", to: "family_tree#index"
  get "family_tree/:id", to: "family_tree#show", as: :family_tree_member

  get "profile", to: "profile#my", as: "my_profile"
  get "profile/edit", to: "profile#edit", as: "edit_profile"
  patch "profile/update", to: "profile#update", as: "update_profile"

  resources :profile, only: [ :show ]

  # CRUD для родственников
  resources :family_members

  # CRUD для воспоминаний
  resources :memories do
    collection do
      get "my"
      get "by_tag/:tag", to: "by_tag", as: "by_tag"
    end
  end

  # Комментарии
  resources :comments, only: [ :show, :create, :edit, :update, :destroy ]

  # Админская часть
  namespace :admin do
    # Страницы просмотра
    get "timeline", to: "memories#timeline"
    get "family_web", to: "memories#family_web"
    get "family_tree", to: "family_tree#index"
    get "family_tree/:id", to: "family_tree#show", as: :admin_family_tree_member

    # CRUD для родственников
    resources :family_members

    # CRUD для воспоминаний
    resources :memories do
      resources :comments
    end

    # Подписки
    resources :subscriptions
  end

  # API
  namespace :api, format: "json" do
    namespace :v1 do
      resources :subscriptions
      get "welcome/index"
      get "welcome/preview"

      devise_scope :user do
        post "sign_up",          to: "registrations#create"
        post "sign_in",          to: "sessions#create"
        get  "authorize_by_jwt", to: "sessions#authorize_by_jwt"
        get  "sign_out",         to: "sessions#destroy"
      end
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Главная
  # Defines the root path route ("/")
  root "pages#home"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  # Changes to the importmap will invalidate the etag for HTML responses
  stale_when_importmap_changes

  rescue_from CanCan::AccessDenied do |exception|
    respond_to do |format|
      format.json { head :forbidden }
      format.html { redirect_to root_path, alert: exception.message }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_footer.html.erb
<nav class="Footer">
        <%= link_to 'AETERNA', root_url, id: 'Name' %>
        <div class="LinksAndDate">
            <div class="Pages Footer">
                <div class="PageLink">
                    <%= link_to 'О нас', pages_about_path %>
                    <%= image_tag 'icons/RightIconArrow.svg', class: 'RightIconArrow' %>
                </div>
                <% if user_signed_in? && current_user.admin? %>
                    <div class="PageLink">
                        <%= link_to 'Лента времени', admin_timeline_path %>
                        <%= image_tag 'icons/RightIconArrow.svg', class: 'RightIconArrow' %>
                    </div>
                    <div class="PageLink">
                        <%= link_to 'Сеть', admin_family_web_path %>
                        <%= image_tag 'icons/RightIconArrow.svg', class: 'RightIconArrow' %>
                    </div>
                    <div class="PageLink">
                        <%= link_to 'Cемейное древо', admin_family_tree_path %>
                        <%= image_tag 'icons/RightIconArrow.svg', class: 'RightIconArrow' %>
                    </div>
                    <div class="PageLink">
                        <%= link_to 'Члены семьи', admin_family_members_path %>
                        <%= image_tag 'icons/RightIconArrow.svg', class: 'RightIconArrow' %>
                    </div>
                    <div class="PageLink">
                        <%= link_to 'Подписки', admin_subscriptions_path %>
                        <%= image_tag 'icons/RightIconArrow.svg', class: 'RightIconArrow' %>
                    </div>

                    <% elsif user_signed_in? %>
                     <div class="PageLink">
                        <%= link_to 'Лента времени', admin_timeline_path %>
                        <%= image_tag 'icons/RightIconArrow.svg', class: 'RightIconArrow' %>
                    </div>
                    <div class="PageLink">
                        <%= link_to 'Сеть', admin_family_web_path %>
                        <%= image_tag 'icons/RightIconArrow.svg', class: 'RightIconArrow' %>
                    </div>
                    <div class="PageLink">
                        <%= link_to 'Cемейное древо', admin_family_tree_path %>
                        <%= image_tag 'icons/RightIconArrow.svg', class: 'RightIconArrow' %>
                    </div>
                <% end %>
            </div>
            <p>©Aeterna, 2025</p>
        </div>
        <div class="Authors">
            <p>Чибичик Алёна</p>
            <p>Семеновых Мария</p>
            <p>Ямщикова Виктория</p>
        </div>
</nav>

app/views/application/_menubar.html.erb
<nav class="S_MenuBar">
    <div>
        <%= link_to 'AETERNA', root_url %>
        <div class="Pages">

        <%= link_to pages_about_path, class: "PageLink" do %>
            О нас
            <%= image_tag "icons/RightIconArrow.svg", class: "RightIconArrow" %>
        <% end %>

        <% if user_signed_in? && current_user.admin? %>

            <%= link_to admin_timeline_path, class: "PageLink" do %>
            Лента времени
            <%= image_tag "icons/RightIconArrow.svg", class: "RightIconArrow" %>
            <% end %>

            <%= link_to admin_family_web_path, class: "PageLink" do %>
            Сеть
            <%= image_tag "icons/RightIconArrow.svg", class: "RightIconArrow" %>
            <% end %>

            <%= link_to admin_family_tree_path, class: "PageLink" do %>
            Семейное древо
            <%= image_tag "icons/RightIconArrow.svg", class: "RightIconArrow" %>
            <% end %>

            <%= link_to admin_family_members_path, class: "PageLink" do %>
            Члены семьи
            <%= image_tag "icons/RightIconArrow.svg", class: "RightIconArrow" %>
            <% end %>

            <%= link_to admin_subscriptions_path, class: "PageLink" do %>
            Подписки
            <%= image_tag "icons/RightIconArrow.svg", class: "RightIconArrow" %>
            <% end %>

            <% elsif user_signed_in? %>
                 <%= link_to timeline_path, class: "PageLink" do %>
                Лента времени
                <%= image_tag "icons/RightIconArrow.svg", class: "RightIconArrow" %>
                <% end %>

                <%= link_to family_web_path, class: "PageLink" do %>
                Сеть
                <%= image_tag "icons/RightIconArrow.svg", class: "RightIconArrow" %>
                <% end %>

                <%= link_to family_tree_path, class: "PageLink" do %>
                Семейное древо
                <%= image_tag "icons/RightIconArrow.svg", class: "RightIconArrow" %>
                <% end %>
        <% end %>

        </div>
    </div>

    <div>
        <% if user_signed_in? %>
            <%#= link_to current_user.email, edit_user_registration_path %>
            <%= link_to "Мои воспоминания", my_memories_path %>
            <%= link_to "Профиль", my_profile_path %>
            <%= link_to "Выйти", destroy_user_session_path, data: {"turbo_method": :delete } %>
        <% else %>
            <%= link_to "Войти", new_user_session_path %>
            <%#= link_to "Зарегистрироваться", new_user_registration_path %>
        <% end %>
    </div>
</nav>